Inssoft-proyects/7cdba2d0-e9ad-4a7a-bbdb-a76c50e8e64f

- Controllers/PersonasController.cs
- Views/Personas/_EditarPersona.cshtml
> Iaa 07062023

- Views/Concesionarios/Index.cshtml
- Views/Concesionarios/_CrearConcesionario.cshtml
Correcciones de ortografía en el módulo de concesionarios.
> Correcciones ortografía concesionarios

- Views/Colores/Index.cshtml
- Views/Colores/IndexModal.cshtml
- Views/Colores/_Crear.cshtml
- Views/Colores/_Editar.cshtml
Correcciones en módulo de colores.
> Correcciones en módulo colores, ortografía, edición y cambio de alertas.

- Services/InfraccionesService.cs
- Views/Infracciones/Index.cshtml
Se corrige la consulta y la funcionalidad de la búsqueda de infracciones para hacer filtros excluyentes.
> Correcciones búsqueda de infracciones

- Views/Anexo/Anexo.cshtml
- Views/CapturaAccidentes/AgregarAccidente.cshtml
- Views/CapturaAccidentes/CapturaAaccidente.cshtml
- Views/CapturaAccidentes/_ModalConductor.cshtml
- Views/CapturaAccidentes/_ModalDetalleVehiculos.cshtml
- Views/CatCausasAccidentes/Index.cshtml
- Views/CatCausasAccidentes/_Crear.cshtml
- Views/CatCausasAccidentes/_Editar.cshtml
- Views/Dependencias/Index.cshtml
- Views/Dependencias/IndexModal.cshtml
- Views/Depositos/Depositos.cshtml
- Views/Infracciones/Detail.cshtml
- Views/Infracciones/Update.cshtml
- Views/Inicio/Marca.cshtml
- Views/Inicio/Marca.cshtml.r4
- Views/Vehiculos/Editar.cshtml
- Views/Vehiculos/Index.cshtml
- Views/Vehiculos/_Create.cshtml
cambio de referencias SITTEG por Registro Estatal de Infracciones y Accidentes
> Correcciones mensajes, títulos equivocados, y cambio de referencias SITTEG

- GuanajuatoAdminUsuarios.csproj
- Interfaces/ICrearMultasTransitoClientService.cs
- RESTModels/AnulacionDocumentoRequestModel.cs
- RESTModels/AnulacionDocumentoResponseModel.cs
- RESTModels/CrearMultasTransitoRequestModel.cs
- RESTModels/CrearMultasTransitoResponseModel.cs
- Services/AnulacionDocumentoClientService.cs
- Services/CrearMultasTransitoClientService.cs
CrearMultasTransito
AnulacionDocumento
> Creacion de logica para consumo de web service con store procedures

- Controllers/EstadisticasAccidentesController.cs
- Framework/CatDictionary.cs
- Interfaces/IEstadisticasAccidentesService.cs
- Models/AccidentesBusquedaModel.cs
- Models/BusquedaAccidentesModel.cs
- Services/EstadisticasAccidentesService.cs
- Startup.cs
- Views/EstadisticasAccidentes/Index.cshtml
- Views/EstadisticasAccidentes/_EstadisticasAccidentes.cshtml
Ajuste de filtros y de consulta para consulta de estadísticas accidentes.
> Complemento estadísticas accidentes

- Controllers/LicenciasController.cs
- Controllers/PersonasController.cs
- Entity/DBContextInssoft.cs
- Entity/GuanajuatoIncidenciasMigContext.cs
- Entity/GuanajuatoLicenciasContext.cs
- Interfaces/ICatEntidadesService.cs
- Interfaces/ILicenciasService.cs
- Interfaces/IPersonasService.cs
- Models/LicenciaPersonaDatos.cs
- Models/LicenciaRespuestaPersona.cs
- Models/LicenciaTipoRespuesta.cs
- Services/CatEntidadesService.cs
- Services/LicenciasService.cs
- Services/PersonasService.cs
- Startup.cs
- Views/Personas/Index.cshtml
- appsettings.json
Creación y consumo de servicio de información de personas por medio de bases de datos de licencias. 
Por el momento apunta a bd de dev.
> Servicio licencias

- Controllers/InfraccionesController.cs
- Entity/DBContextInssoft.cs
- Views/Infracciones/Crear.cshtml
- Views/Infracciones/_ListadoPersonasBusqueda.cshtml
- Views/Infracciones/_ModalBusquedaPersonas.cshtml
- appsettings.json
Mantener flujo de captura de infracción al capturar conductores
> Flujo captura conductores

- Controllers/InfraccionesController.cs
- Framework/Catalogs/CatEnumerator.cs
- Interfaces/IInfraccionesService.cs
- Services/CancelarInfraccionService.cs
- Services/InfraccionesService.cs
- Views/RegistroReciboPago/_DetalleRegistroDePago.cshtml
Este rama tiene ajustes en varias funcionalidades que se necesitan en la captura de la infracción.
> Ajustes en la captura de infracción, cancelación, validación de pago, captura de motivos

- Controllers/EstadisticasController.cs
- GuanajuatoAdminUsuarios.csproj
- Interfaces/IEstadisticasService.cs
- Services/CancelarInfraccionService.cs
- Services/EstadisticasService.cs
- Views/Infracciones/_ListadoInfracciones.cshtml
Ajustes estadísticas y cancelación infracción
> ajustes estadisticas

- Controllers/BusquedaAccidentesController.cs
- Controllers/CapturaAccidentesController.cs
- Interfaces/IBusquedaAccidentesService.cs
- Models/BusquedaAccidentesPDFModel.cs
- Services/BusquedaAccidentesService.cs
- Views/BusquedaAccidentes/Index.cshtml
- Views/BusquedaAccidentes/_ListaAccidentesBusqueda.cshtml
- Views/CapturaAccidentes/_ListadoAccidentes.cshtml
- Views/CapturaAccidentes/_ListadoInvolucrados.cshtml
- Views/CapturaAccidentes/_ModalCapturarConductor.cshtml
- Views/CatClasificacionAccidentes/_Crear.cshtml
- Views/Personas/_EditarPersona.cshtml
- Views/Shared/_Layout.cshtml
- Views/Vehiculos/_Create.cshtml
Fix Tikets accidentes 6406,6468,6415,6459,6457,6455,6414,6481,6456
> Fix Tikets accidentes 6406,6468,6415,6459,6457,6455,6414,6481,6456

- Views/Anexo/Anexo.cshtml
- Views/CapturaAccidentes/_Create.cshtml
- Views/Infracciones/_Create.cshtml
> Fix bug 6457

- Controllers/InfraccionesController.cs
- Framework/CatDictionary.cs
- Framework/Catalogs/CatWebServicesEnumerator.cs
- Interfaces/IApiClientDatabaseService.cs
- Interfaces/IAppSettingsService.cs
- Interfaces/ICatDictionary.cs
- Interfaces/IRepuveService.cs
- Models/AppSettingsModel.cs
- RESTModels/RepuveConsgralRequestModel.cs
- RESTModels/RepuveConsgralResponseModel.cs
- Services/ApiClientDatabaseService.cs
- Services/AppSettingService.cs
- Services/RepuveService.cs
- Startup.cs
Repuve infracciones consulta general vehículo
> Repuve infracciones consulta general vehículo

- Services/EstadisticasService.cs
> Fix BUG 6484

- Controllers/CapturaAccidentesController.cs
- Controllers/InfraccionesController.cs
- Controllers/VehiculosController.cs
- GuanajuatoAdminUsuarios.csproj
- Helpers/ControllerExtensions.cs
- Views/CapturaAccidentes/CapturaAaccidente.cshtml
- Views/CapturaAccidentes/_Create.cshtml
- Views/CapturaAccidentes/_ModalVehiculo.cshtml
> 20230924 iaa

- Views/CancelarInfraccion/CancelarInfraccion.cshtml
aqui se atienden las pruebas de los comentarios
> Fixprueba modulo que integra una prueba

- Controllers/TransitoTransporteController.cs
- Services/TransitoTransporteService.cs
- Views/TransitoTransporte/_ListadoTransitoTransporte.cshtml
- wwwroot/js/GenericComponents.js
> Fix Ticket 6605

- Controllers/CapturaAccidentesController.cs
- Controllers/InfraccionesController.cs
- Controllers/VehiculosController.cs
- RESTModels/RepuveConsRoboResponseModel.cs
> Dbh sitteg

- Controllers/InfraccionesController.cs
- Entity/InfoInfraccion.cs
- Interfaces/IInfraccionesService.cs
- Models/DefaultsModels.cs
- Models/InfraccionesBusquedaEspecialModel.cs
- Models/PersonaInfraccionModel.cs
- Models/PersonaModel.cs
- Services/InfraccionesService.cs
- Views/Infracciones/BusquedaEspecial.cshtml
- Views/Infracciones/Mostrar.cshtml
- Views/Infracciones/_ListadoInfraccionesBusquedaEspecial.cshtml
- Views/Shared/_Layout.cshtml
- wwwroot/js/Infracciones/BusquedaEspecial/BusquedaEspecial.js
- wwwroot/js/Infracciones/BusquedaEspecial/Funcionality/ConexxionPeticiones.js
- wwwroot/js/Infracciones/BusquedaEspecial/Peticiones/PeticionDatosGrid.js
- wwwroot/js/Infracciones/BusquedaEspecial/Templates/Templates.js
creacion de la pantalla y todo lo nesesario para su visualizacion
> pantalla Busqueda especial

- Controllers/InfraccionesController.cs
- Models/PersonaModel.cs
- Views/Infracciones/Crear.cshtml
- Views/Infracciones/_CrearPersona.cshtml
Correciones loading infracciones
> Correciones loading infracciones

- Controllers/CapturaAccidentesController.cs
- Controllers/InfraccionesController.cs
- GuanajuatoAdminUsuarios.csproj
- Models/CapturaAccidentesModel.cs
- Services/CapturaAccidentesService.cs
- Services/CortesiasNoAplicadasService.cs
- Views/CapturaAccidentes/CapturaAaccidente.cshtml
- Views/CapturaAccidentes/_Create.cshtml
- Views/CapturaAccidentes/_ListPersonasMorales.cshtml
- Views/CapturaAccidentes/_ListaCausas.cshtml
- Views/CapturaAccidentes/_ModalConductor.cshtml
- Views/CapturaAccidentes/_ModalDetalleVehiculos.cshtml
- Views/CapturaAccidentes/_PersonasFisicas.cshtml
- Views/CortesiasNoAplicadas/_DetalleCortesiasNoAplicadas.cshtml
- Views/Infracciones/_Create.cshtml
- Views/Infracciones/_DetallePersona.cshtml
- Views/Infracciones/_PersonasFisicas.cshtml
- Views/Shared/_Layout.cshtml
- Views/Shared/_UpdatePersonaMoral.cshtml
se atienden incidencias:
id 22
id 79
> Correccion en consulta stopper, fix ids 22,79

- Views/Infracciones/_CrearPersona.cshtml
- Views/Shared/_Layout.cshtml
Merge con los cambios de Diana
> Merge - diana

- GuanajuatoAdminUsuarios.csproj
- Views/CapturaAccidentes/_PersonasFisicas.cshtml
- Views/Infracciones/_PersonasFisicas.cshtml
- Views/Personas/_EditarPersona.cshtml
- Views/Vehiculos/_Create.cshtml
- Views/Vehiculos/_PersonasFisicas.cshtml
Se hacen modificaciones para resolver bloqueo en selección de vehículo involucrado en accidentes
> fix bloqueo flujo accidentes

- Controllers/PersonasController.cs
- Controllers/VehiculosController.cs
- GuanajuatoAdminUsuarios.csproj
- Views/CapturaAccidentes/_ListaDetalleVehiculo.cshtml
- Views/CapturaAccidentes/_ModalAgregarInvolucrado.cshtml
- Views/CapturaAccidentes/_ModalInvolucrado-Vehiculo.cshtml
- Views/Personas/Index.cshtml
- Views/Personas/_CrearPersona.cshtml
- Views/Personas/_EditarPersona.cshtml
- Views/Vehiculos/_UpdatePersonaMoral.cshtml
Se atienden los items:
-QA22
-QA39
-QA41
- corrección de flujo editar persona en modulo personas
> Fix incidencias QA 1312

- Views/CapturaAccidentes/_ModalAgregarInvolucrado.cshtml
> Fix busqueda persona accidentes

- Services/InfraccionesService.cs
- Views/Infracciones/_CrearPersona.cshtml
- Views/Infracciones/_Create.cshtml
- Views/Inicio/Marca.cshtml
- wwwroot/js/site.js
Validaciones generales y busqueda especial Propietario y Conductor
> Validaciones

- Controllers/BusquedaAccidentesController.cs
- Controllers/BusquedaEspecialAccidentesController.cs
- GuanajuatoAdminUsuarios.csproj
- Services/BusquedaAccidentesService.cs
- Services/BusquedaEspecialAccidentesService.cs
- Views/BusquedaEspecialAccidentes/Index.cshtml
- Views/BusquedaEspecialAccidentes/_ListaAccidentesBusquedaEspecial.cshtml
Se atiende incidencias unicamente de QA
QA49
QA51
QA54
> Fix incidencias qa1512

- GuanajuatoAdminUsuarios.csproj
- Models/DatosAccidenteModel.cs
- Services/CapturaAccidentesService.cs
- Views/CapturaAccidentes/CapturaCAccidente.cshtml
- Views/PadronGruas/_ListadoGruas.cshtml
- Views/Vehiculos/_Create.cshtml
Se atiende incidencias:
QA 57
QA 63
QA 64
QA 65
QA 69
> Ajustes a campos numericos de accidentes

- Controllers/VehiculosController.cs
- GuanajuatoAdminUsuarios.csproj
- Services/VehiculosService.cs
- Views/CapturaAccidentes/CapturaCAccidente.cshtml
- Views/EnvioInfracciones/_ModalEnvioInfracciones.cshtml
- Views/Personas/_EditarPersona.cshtml
- Views/SalidaVehiculos/DatosDeposito.cshtml
- Views/SalidaVehiculos/_ModalCostosServicio.cshtml
- Views/Shared/_EditarPersona.cshtml
- Views/Vehiculos/_Create.cshtml
- wwwroot/css/main.css
Se resuelve error al abrir modal editar persona física, si atiende incidencia QA 72
> Fix depositos salida vehiculos

- Views/AsignacionGruas/capturaGruas.cshtml
- Views/BusquedaDeposito/Index.cshtml
- Views/CapturaAccidentes/CapturaCAccidente.cshtml
- Views/Infracciones/Editar.cshtml
- Views/Infracciones/Editar2.cshtml
- Views/Infracciones/_Cortesia.cshtml
- Views/IngresarVehiculo/Index.cshtml
- Views/IngresarVehiculo/IngresoTransitoTransporte.cshtml
- Views/LiberacionVehiculo/_UpdateLiberacion.cshtml
- Views/SalidaVehiculos/DatosServicio.cshtml
- Views/SalidaVehiculos/Index.cshtml
- Views/SalidaVehiculos/_ModalCostosServicio.cshtml
- Views/TransitoTransporte/_ListadoTransitoTransporte.cshtml
- Views/Vehiculos/_Create.cshtml
> Ajustes de alineación

- Models/CapturaAccidentesModel.cs
- Services/CapturaAccidentesService.cs
- Services/VehiculosService.cs
- Views/CapturaAccidentes/_Create.cshtml
- Views/CapturaAccidentes/_ModalComplementoVehiculo.cshtml
- Views/CapturaAccidentes/_ModalConductor.cshtml
- Views/CapturaAccidentes/_ModalDetalleVehiculos.cshtml
- Views/Infracciones/_Create.cshtml
- Views/Vehiculos/_Create.cshtml
Cambios despues de corregir error en mi rama
> Nueva rama fix

- Controllers/CapturaAccidentesController.cs
- Models/CapturaAccidentesModel.cs
- Services/CapturaAccidentesService.cs
- Views/CapturaAccidentes/_InfoPrevioInvolucrados.cshtml
- Views/CapturaAccidentes/_ModalCrearInfraccion.cshtml
- Views/CapturaAccidentes/_ModalDetalleVehiculos.cshtml
- Views/Infracciones/Editar.cshtml
Se atiende incidencias:
QA84
QA90
> Fecha nacimiento involucrados fix

- Controllers/CapturaAccidentesController.cs
- GuanajuatoAdminUsuarios.csproj
- Models/CapturaAccidentesModel.cs
- Services/CapturaAccidentesService.cs
- Views/CapturaAccidentes/CapturaCAccidente.cshtml
- Views/CapturaAccidentes/_InfoPrevioInvolucrados.cshtml
- Views/CapturaAccidentes/_ModalCrearInfraccion.cshtml
- Views/CapturaAccidentes/_ModalDetalleVehiculos.cshtml
- Views/Infracciones/Editar.cshtml
Se atiende tema debotones que se desajustaron y se resuleve error encontrado en un query
> Fix botones rehacer

- Views/Infracciones/BusquedaEspecial.cshtml
- Views/Infracciones/_ListadoInfraccionesBusquedaEspecial.cshtml
- wwwroot/js/Infracciones/BusquedaEspecial/BusquedaEspecial.js
Se atienden incidencias:
QA88
QA89
> Ajustes busqueda especial infracciones

- Controllers/InfraccionesController.cs
- Interfaces/IInfraccionesService.cs
- Models/GarantiaInfraccionModel.cs
- Services/InfraccionesService.cs
- Views/CapturaAccidentes/_ListaInfraccionesAccidente.cshtml
- Views/Infracciones/Editar.cshtml
-Se realizan cambios en guardado y consulta de garantia
-Se Hacen ajustes a la asignacion de infraccion desde accidentes
> Cambio filtrado accidentes por dependencia

- Controllers/CapturaAccidentesController.cs
- Controllers/InfraccionesController.cs
- Interfaces/IInfraccionesService.cs
- Services/CapturaAccidentesService.cs
- Services/InfraccionesService.cs
- Views/Shared/_Layout.cshtml
Cambios en idPersonaInfraccion todos los flujos 
Cambios en ids del menu segun la reunion
> Ajustes id persona infraccion

- Models/CapturaAccidentesModel.cs
- Services/CapturaAccidentesService.cs
- Services/InfraccionesService.cs
- Views/CapturaAccidentes/_ListaDetalleVehiculo.cshtml
- Views/CapturaAccidentes/_ListaVehiculosInvolucrados.cshtml
- Views/Infracciones/Editar.cshtml
- Views/Infracciones/_CrearPersona.cshtml
- Views/Infracciones/_ModalBusquedaPersonas.cshtml
- Views/Inicio/Marca.cshtml
- Views/SalidaVehiculos/DatosDeposito.cshtml
Se atienden incidencias:
QA 95
QA 103
QA 113
QA114
> Fix infracciones validas

- Controllers/BusquedaAccidentesController.cs
- Controllers/LoginController.cs
- CustomClaims.cs
- Interfaces/ICatDelegacionesOficinasTransporteService.cs
- Interfaces/IConcesionariosService.cs
- Models/MotivosInfraccionVistaModel.cs
- Services/CatDelegacionesOficinasTransporteService.cs
- Services/ConcesionariosService.cs
- Views/BusquedaAccidentes/_ListaAccidentesBusqueda.cshtml
- Views/Concesionarios/Index.cshtml
- Views/Infracciones/_ListadoMotivos.cshtml
- Views/Shared/EditorTemplates/NumericTextBox.cshtml
- Views/Shared/_Layout.cshtml
Se hacen modificaciones para mostrar en el front el nombre y oficina del usuario
> Fix incidencias08 enero

- Controllers/LoginController.cs
Se hace cambio de url para servicio login
> Cambio url servicio login

- Services/CapturaAccidentesService.cs
- Views/CapturaAccidentes/_ListaInvolucrados.cshtml
- Views/CapturaAccidentes/_ListadoInvolucrados.cshtml
- Views/Infracciones/Editar.cshtml
- Views/Infracciones/_CrearMotivo.cshtml
- Views/Infracciones/_ListadoMotivos.cshtml
- Views/Infracciones/_ModalEliminarMotivo.cshtml
- wwwroot/css/main.css
Se atienden QAs degradadas y se corrige error que no permitía guardar motivos de infracción
> Ajustes incidencias degraddas, ya permite guardar motivos

- GuanajuatoAdminUsuarios.csproj
- Views/AsignacionGruas/_ListaGruas.cshtml
- Views/AsignacionGruas/_ListaSolicitudes.cshtml
- Views/CatAgenciasMinisterio/Index.cshtml
- Views/CatAutoridadesDisposicion/Index.cshtml
- Views/CatAutoridadesEntrega/Index.cshtml
- Views/CatCarreteras/Index.cshtml
- Views/CatCausasAccidentes/Index.cshtml
- Views/CatClasificacionAccidentes/Index.cshtml
- Views/CatDelegacionesOficinasTransporte/Index.cshtml
- Views/CatEntidades/Index.cshtml
- Views/CatFactoresAccidentes/Index.cshtml
- Views/CatFactoresOpcionesAccidentes/Index.cshtml
- Views/CatHospitales/Index.cshtml
- Views/CatInstitucionesTraslado/Index.cshtml
- Views/CatMarcasVehiculos/Index.cshtml
- Views/CatMunicipios/Index.cshtml
- Views/CatOficinasRenta/Index.cshtml
- Views/CatTramos/Index.cshtml
- Views/Colores/Index.cshtml
- Views/Inicio/Marca.cshtml
- Views/LiberacionVehiculo/_ListadoVehiculos.cshtml
- Views/Shared/_Layout.cshtml
- Views/Vehiculos/_ListVehiculos.cshtml
> Ajuste de alineación

- Views/MotivosInfraccion/_Crear.cshtml
- Views/MotivosInfraccion/_Editar.cshtml
> Ajustes de alineacion

- Controllers/DiasInhabilesController.cs
- Interfaces/IDiasInhabiles.cs
- Services/CatTramosService.cs
- Services/DiasInhabilesService.cs
- Services/LiberacionVehiculoService.cs
- Services/OficialesService.cs
- Startup.cs
- Utils/CatalogosEnums.cs
- Views/CatTramos/Index.cshtml
- Views/DiasInhabiles/Index.cshtml
- Views/Infracciones/Index.cshtml
Se atiende varias incidencias QA reportadas por alfonso
> Revision QA alfonso

- Controllers/PadronGruasController.cs
- Interfaces/IConcesionariosService.cs
- Services/ConcesionariosService.cs
- Views/PadronGruas/Index.cshtml
Segunda parte atencion QAs 2 de febrero
> Revision infracciones

- Controllers/TransitoTransporteController.cs
- Framework/CatDictionary.cs
- Services/BusquedaDepositoService.cs
- Services/InfraccionesService.cs
- Services/SalidaVehiculosService.cs
- Services/TransitoTransporteService.cs
- Views/Personas/Index.cshtml
Se corrige guardado y muetrar fecha de infraccion
Se corrige filtrado de fechas en busqueda deposito, salida vehiculo y busqueda transito y transporte
> Incidencias0302

- Controllers/CatTramosController.cs
- Services/CatCarreterasService.cs
- Services/ComparativoInfraccionesService.cs
- Views/CatTramos/Index.cshtml
- Views/ComparativoInfracciones/_ComparativoInfraccionesResultados.cshtml
Se atiende 
QA 221 
QA 222 
Revision y correccion de query de comparativo de infracciones
> Ajuste QAs Alfonso

- Controllers/AsignacionGruasController.cs
- Controllers/InfraccionesController.cs
- GuanajuatoAdminUsuarios.csproj
- Interfaces/IAsignacionGruasService.cs
- Interfaces/IInfraccionesService.cs
- Services/AsignacionGruasService.cs
- Services/InfraccionesService.cs
- Views/Infracciones/Editar.cshtml
- Views/TransitoTransporte/_ListadoTransitoTransporte.cshtml
- appsettings.json
Los archivos se crean en filesystem en lugar de almacenarse en la base de datos para los siguientes módulos:
* Infracciones
* Depositos
La ruta de la carpeta de los archivos se almacenan en appsettings.json, por lo que si la ruta cambia es necesario actualizarlas
> Los documentos de inventario de infracciones y depositos se crean en filesystem

- Controllers/AsignacionGruasController.cs
- Controllers/InfraccionesController.cs
- ILoggerManager.cs
- LoggerManager.cs
- Services/PersonasService.cs
- Startup.cs
- appsettings.json
- log4net.config
Se agregó log4j para la carga de inventario en infracciones y depósitos
> Log4j Documentos inventario

- Controllers/InfraccionesController.cs
- Interfaces/IInfraccionesService.cs
- Models/VehiculoModel.cs
- Services/InfraccionesService.cs
- Views/Infracciones/Crear.cshtml
- Views/Infracciones/Editar.cshtml
- Views/Infracciones/_DetalleVehiculo.cshtml
- Views/Infracciones/_ListadoPersonas.cshtml
- wwwroot/css/main.css
> QA 302 y 301

- Controllers/DepositosController.cs
- Controllers/InfraccionesController.cs
- Controllers/LoginController.cs
- CustomClaims.cs
- Enums/DependenciaEnum.cs
- Interfaces/IDelegacionesService.cs
- Interfaces/IDepositosService.cs
- Services/DelegacionesService.cs
- Services/DepositosService.cs
- Views/Depositos/Depositos.cshtml
Se creo la nomenclatura para el folio de solicitud de deposito de acuerdo a la siguiente:
GU00001/24-TTO  --- Ejemplo nomenclatura PEC
AC00001/24-TPTE --- Ejemplo nomenclatura Movilidad
Abreviatura Municipio+consecutivo 5 caracteres+"/"año+"-"TTO(para PEC)TPTE(Para movilidad)
> QA-342 Nomeclatura deposito

- Controllers/PDFGeneratorController.cs
- Views/Colores/_Crear.cshtml
- Views/Vehiculos/_Create.cshtml
- wwwroot/css/main.css
> 338, 352, 317

- CustomClaims.cs
- Services/PensionesService.cs
> problemas de delegacion en pensiones

- Views/RegistroReciboPago/_DetalleRegistroDePago.cshtml
Se ajusto los cols y el boton de cancelar
> Ajuste en el col

- Controllers/CatMunicipiosController.cs
- Controllers/CatOficinasRentaController.cs
- Controllers/CatTramosController.cs
- Controllers/OficialesController.cs
- Controllers/SalariosMinimosController.cs
- Entity/Delegaciones.cs
- Models/CatCarreterasModel.cs
- Models/CatDelegacionesOficinasTransporteModel.cs
- Models/CatOficinasRentaModel.cs
- Services/CatCarreterasService.cs
- Services/CatDelegacionesOficinasTransporteService.cs
- Services/DelegacionesService.cs
- Services/TransitoTransporteService.cs
- Views/CatOficinasRenta/_Editar.cshtml
- Views/CatTramos/_Crear.cshtml
- Views/Oficiales/_Crear.cshtml
- Views/Oficiales/_Editar.cshtml
- Views/SalariosMinimos/_Crear.cshtml
- Views/SalariosMinimos/_Editar.cshtml
- Views/SalariosMinimos/_ListaSalariosMinimos.cshtml
> 384, 385, 386, 387, 389

- Controllers/PDFGeneratorController.cs
- Controllers/TransitoTransporteController.cs
- GuanajuatoAdminUsuarios.csproj
- Interfaces/IInfraccionesService.cs
- Services/BusquedaAccidentesService.cs
- Services/InfraccionesService.cs
- Views/BusquedaAccidentes/Index.cshtml
- Views/Infracciones/Index.cshtml
* Se modificó el SP para generar reporte, se agregó uno nuevo
* Se agregó un nuevo método para generar reporte PDF
*  Se agregaron indices a la bd
> PDF Busqueda de Infracciones

- Controllers/ComparativoInfraccionesController.cs
- Controllers/OficialesController.cs
- Framework/CatDictionary.cs
- Interfaces/IOficiales.cs
- Models/ComparativoInfraccionesModel.cs
- Models/SystemCatalogModel.cs
- Services/OficialesService.cs
- Views/ComparativoInfracciones/Index.cshtml
- Views/EstadisticasAccidentes/Index.cshtml
> 423,  425, 426

- Controllers/InfraccionesController.cs
- Controllers/LiberacionVehiculoController.cs
- GuanajuatoAdminUsuarios.csproj
- Interfaces/IPersonasService.cs
- Models/PersonaModel.cs
- Services/PersonasService.cs
- Views/Infracciones/Editar.cshtml
- Views/Infracciones/_DetallePersona.cshtml
- appsettings.json
> 2.-EDITAR DATOS DE CONDUCTOR

- Views/Infracciones/_Create.cshtml
se ingora propietario Infracciones
> se ingora propietario Infracciones

- Services/GruasService.cs
- Views/PadronGruas/_CrearGrua.cshtml
> qa 284 y 195

- Controllers/AsignacionGruasController.cs
- Services/AsignacionGruasService.cs
> Captura de gruas 1.-

- Controllers/DepositosController.cs
- Views/Depositos/Depositos.cshtml
> QA 284 450

- Components/ListaPersonasEncontradasViewComponent.cs
- Controllers/BusquedaVehiculoPropietarioController.cs
- Interfaces/IPersonasService.cs
- Models/BusquedaPersonaModel.cs
- Services/IngresoVehiculosService.cs
- Services/PersonasService.cs
- Views/CapturaAccidentes/_Create.cshtml
- Views/Shared/Components/ListaPersonasEncontradas/ListaPersonasEncontradas.cshtml
- Views/Shared/Components/ListaPersonasEncontradasOtras/ListaPersonasEncontradasOtras.cshtml
- Views/Shared/_Vehiculo.cshtml
Se revisaron flujos de consulta de personas y vehículos
* Se guardan los campos que faltaban en deposito de otra dependencia
> QA-471,QA-287,QA-477

- Controllers/BusquedaAccidentesController.cs
- Services/LiberacionVehiculoService.cs
- Views/AsignacionGruas/_ModalAgregarGrua.cshtml
- Views/AsignacionGruas/_ModalEditarGrua.cshtml
- Views/DepositosOtraDependencia/DepositosOtraDependencia.cshtml
- Views/Infracciones/Editar2.cshtml
- Views/Infracciones/_DetallePersona.cshtml
- Views/Infracciones/_EditarDetalleVehiculo.cshtml
- Views/RegistroReciboPago/_DetalleRegistroDePago.cshtml
> QA 465 466

- Controllers/CapturaAccidentesController.cs
- Controllers/CatCarreterasController.cs
- Views/BusquedaAccidentes/Index.cshtml
- Views/BusquedaEspecialAccidentes/Index.cshtml
- Views/CapturaAccidentes/CapturaCAccidente.cshtml
- Views/Infracciones/Editar.cshtml
491, 496, 518, 494, la 520 se validó en conjunto con QA y funciona correctamente.
> 491, 496, 518 y 494

- Controllers/AsignacionGruasController.cs
- Controllers/CapturaAccidentesController.cs
- Controllers/InfraccionesController.cs
- Models/CapturaAccidentesModel.cs
- Models/SolicitudDepositoModel.cs
- Services/CapturaAccidentesService.cs
- Services/DepositosService.cs
- Services/GruasService.cs
- Views/AsignacionGruas/_ModalAgregarGrua.cshtml
- Views/CapturaAccidentes/_Create.cshtml
- Views/CapturaAccidentes/_InfoPrevioInvolucrados.cshtml
- Views/CapturaAccidentes/_ListadoInvolucrados.cshtml
- Views/CapturaAccidentes/_ModalInvolucrado-Vehiculo.cshtml
- Views/Depositos/Depositos.cshtml
- Views/Infracciones/Crear.cshtml
- Views/Infracciones/_CrearPersona.cshtml
-Comentario QI 8
-Comentario QI 18
-Comentario QI 22
-Fix QI 21
-QI 70
-QI 72
-QI 73
> Varias QI y Fixes

- Controllers/BusquedaVehiculoPropietarioController.cs
- Views/Shared/_BusquedaVehiculoPropietario.cshtml
- Views/Shared/_Vehiculo.cshtml
> QI 19 otra dependencia

- Services/CapturaAccidentesService.cs
usp_ObtieneVehiculosInvolucrados
> usp_ObtieneVehiculosInvolucrados

- Views/Infracciones/Crear.cshtml
- Views/Infracciones/Editar.cshtml
Ajuste para que no se descuadre
> Ajuste en cols

- Controllers/InfraccionesController.cs
- Interfaces/IInfraccionesService.cs
- Services/InfraccionesService.cs
- Views/Infracciones/Editar.cshtml
- Views/Infracciones/_EditarDetalleVehiculo.cshtml
- Views/Infracciones/_ListadoPersonas.cshtml
QA 4 - Vehículos propietarios / Conductor
> QA 4 - Vehículos propietarios / Conductor
